from time import sleep
from utilities import *

def threeDeepBreaths():
    run_seq("reset")
    sleep(2)
    run_seq("sad_shrink")
    sleep(2)
    run_seq("reset")
    sleep(1)
    run_seq("sad_shrink")
    sleep(2)
    run_seq("reset")
    sleep(2)
    run_seq("sad_shrink")
    sleep(2)
    run_seq("reset")
    sleep(1)
    run_seq("sad_shrink")
    sleep(5)

init_robot()

run_seq("reset")
sleep(2)
threeDeepBreaths()
# run_seq("sad_shrink")
# sleep(5)
# run_seq("azcustom/deepBreath")
# sleep(5)
# run_seq("sad_shrink")
# sleep(5)
# run_seq("azcustom/deepBreath")
# sleep(5)
# run_seq("sad_shrink")
# sleep(5)
# run_seq("azcustom/deepBreath")
# sleep(5)
# run_seq("sad_shrink")
# sleep(5)
#run_seq("azcustom/deepBreath")
# run_seq("yes")
# sleep(5)
# run_seq("happy")
# sleep(5)
# run_seq("sad")
# sleep(10)
